<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>transfer-service</artifactId>
        <groupId>com.brunosong.transfer.system</groupId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>transfer-container</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-application-service</artifactId>
        </dependency>
        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-domain-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-dataaccess</artifactId>
        </dependency>
        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-infrastructure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-messaging</artifactId>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.33</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bus-kafka</artifactId>
        </dependency>

        <dependency>
            <groupId>com.brunosong.transfer.system</groupId>
            <artifactId>transfer-cache</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <from>
                        <image>openjdk:21-jdk-slim</image> <!-- 사용할 베이스 이미지 -->
                    </from>
                    <to>
                        <image>airtrack1234/transfer.service:1.0.3</image> <!-- 푸시할 이미지 이름 -->
                    </to>
                    <container>
                        <mainClass>com.brunosong.transfer.system.main.TransferSystemApplication</mainClass> <!-- Spring Boot 메인 클래스 -->
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>


</project>