<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <modules>
        <module>data-migration-service</module>
        <module>transfer-service</module>
        <module>common</module>
        <module>dataupload-service</module>
        <module>infrastructure</module>
        <module>metaupload-service</module>
    </modules>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.12</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.brunosong.transfer.system</groupId>
    <artifactId>transfer-system</artifactId>
    <version>1.0</version>
    <name>TransferSystem</name>
    <description>TransferSystem</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <properties>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>17</java.version>
        <kafka-avro-serializer.version>7.0.1</kafka-avro-serializer.version>
        <spring-kafka.version>2.8.2</spring-kafka.version>
        <avro.version>1.11.0</avro.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-domain-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-application-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-dataaccess</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-messaging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-container</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>data-migration-application</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-container</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-dataaccess</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-messaging</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-domain-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-application-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-application</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>transfer-infrastructure</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>common-dataaccess</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>common-domain</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>common-application</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>dataupload-domain-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>dataupload-application-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>metaupload-domain-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>metaupload-cache</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>metaupload-application-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>metaupload-dataaccess</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>dataupload-container</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>kafka-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>kafka-producer</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>kafka-config-data</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.brunosong.transfer.system</groupId>
                <artifactId>kafka-consumer</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <release>17</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.ferstl</groupId>
                <artifactId>depgraph-maven-plugin</artifactId>
                <version>4.0.2</version>
                <configuration>
                    <createImage>true</createImage>
                    <showGroupIds>true</showGroupIds>
                    <showVersions>true</showVersions>
                    <showDuplicates>true</showDuplicates>
                    <showConflicts>true</showConflicts>
                </configuration>
            </plugin>
        </plugins>
    </build>



</project>
