spring:
  application:
    name: BrunosongTransferSystem

  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#      max-poll-records: 1 # 한건에 리스트를 보낼것이고 리스트에 시간이 많이 걸리기에 한건만 가져온다
#      max-poll-interval-ms: 600000 # 메시지를 처리할 최대 시간 (10분)
#      enable-auto-commit: false   # 자동으로 커밋하는걸 방지하여
#      auto-offset-reset: earliest  # offset 커밋내역이 없으면 offset 첨부터 읽어 들인다



  # JPA Properties Setting
  aiservice-jpa:
    scan-package-path: com.brunosong.transfersystem.aiservice.infrastructure
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: com.brunosong.transfersystem.config.jpa.ImprovedNamingStrategy
    show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    defer-datasource-initialization: true

  main-jpa:
    scan-package-path: com.brunosong.transfersystem.main.domain
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: com.brunosong.transfersystem.config.jpa.ImprovedNamingStrategy
    show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    defer-datasource-initialization: true

  datasource:
    main:
      # Transfer Service (Main)
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:main;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password:
      initialization-mode: never

    # AI Service Real
    # The Real DDL is not working because the JPA setting on aiServiceDynamicDataSource is using the default aiservice-dev datasource for DDL creation.
    aiservice-real:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:aiserviceReal;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password:
      initialization-mode: never

    # AI Service Dev
    aiservice-dev:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:aiserviceDev;DB_CLOSE_DELAY=-1;MODE=MySQL
      username: sa
      password:
      initialization-mode: never


logging:
  level:
    org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql: TRACE



