spring:
  application:
    name: transfer-service
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      id: ${spring.application.name}:${spring.profiles.active:local}:${random.uuid}
    compatibility-verifier:
      enabled: false
    config:
      profile: default
  sql:
    init:
      mode: always
      schema-locations: classpath:init-schema.sql
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/exampledb?authSource=admin
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: brunosong
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        generate_statistics: true
  kafka:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092


management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
#    org.springframework.cloud: DEBUG
#    org.springframework.kafka: DEBUG
#    org.springframework.cloud.bus: TRACE