{
  "namespace": "com.brunosong.transfer.system.kafka.transfer.avro.model",
  "type": "record",
  "name": "LearningMaterialAvroModel",
  "fields": [
    {
      "name": "id",
      "type": {
        "type": "string"
      }
    },
    {
      "name": "title",
      "type": {
        "type": "string"
      }
    },
    {
      "name": "description",
      "type": {
        "type": "string"
      }
    },
    {
      "name": "metadataList",
      "type": {
        "type": "array",
        "items":{
          "name":"LearningMaterialMetadataAvroModel",
          "type":"record",
          "fields":[
            {"name":"attributeName", "type": "string"},
            {"name":"attributeValue", "type": "string"}
          ]
        }
      }
    }
  ]
}