/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.brunosong.transfer.system.kafka.transfer.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DataMigrationRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5601505765301635678L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataMigrationRequestAvroModel\",\"namespace\":\"com.brunosong.transfer.system.kafka.transfer.avro.model\",\"fields\":[{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"dataMigrationId\",\"type\":\"long\"},{\"name\":\"transferId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"SourceContentData\",\"type\":{\"type\":\"record\",\"name\":\"SourceContentDataAvroModel\",\"fields\":[{\"name\":\"sourceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"jsonData\",\"type\":\"bytes\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DataMigrationRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<DataMigrationRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DataMigrationRequestAvroModel> DECODER =
      new BinaryMessageDecoder<DataMigrationRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DataMigrationRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DataMigrationRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DataMigrationRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DataMigrationRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DataMigrationRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DataMigrationRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DataMigrationRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DataMigrationRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String sagaId;
  private long dataMigrationId;
  private java.lang.String transferId;
  private com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel SourceContentData;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DataMigrationRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param sagaId The new value for sagaId
   * @param dataMigrationId The new value for dataMigrationId
   * @param transferId The new value for transferId
   * @param SourceContentData The new value for SourceContentData
   */
  public DataMigrationRequestAvroModel(java.lang.String sagaId, java.lang.Long dataMigrationId, java.lang.String transferId, com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel SourceContentData) {
    this.sagaId = sagaId;
    this.dataMigrationId = dataMigrationId;
    this.transferId = transferId;
    this.SourceContentData = SourceContentData;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sagaId;
    case 1: return dataMigrationId;
    case 2: return transferId;
    case 3: return SourceContentData;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sagaId = value$ != null ? value$.toString() : null; break;
    case 1: dataMigrationId = (java.lang.Long)value$; break;
    case 2: transferId = value$ != null ? value$.toString() : null; break;
    case 3: SourceContentData = (com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'dataMigrationId' field.
   * @return The value of the 'dataMigrationId' field.
   */
  public long getDataMigrationId() {
    return dataMigrationId;
  }


  /**
   * Sets the value of the 'dataMigrationId' field.
   * @param value the value to set.
   */
  public void setDataMigrationId(long value) {
    this.dataMigrationId = value;
  }

  /**
   * Gets the value of the 'transferId' field.
   * @return The value of the 'transferId' field.
   */
  public java.lang.String getTransferId() {
    return transferId;
  }


  /**
   * Sets the value of the 'transferId' field.
   * @param value the value to set.
   */
  public void setTransferId(java.lang.String value) {
    this.transferId = value;
  }

  /**
   * Gets the value of the 'SourceContentData' field.
   * @return The value of the 'SourceContentData' field.
   */
  public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel getSourceContentData() {
    return SourceContentData;
  }


  /**
   * Sets the value of the 'SourceContentData' field.
   * @param value the value to set.
   */
  public void setSourceContentData(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel value) {
    this.SourceContentData = value;
  }

  /**
   * Creates a new DataMigrationRequestAvroModel RecordBuilder.
   * @return A new DataMigrationRequestAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder newBuilder() {
    return new com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder();
  }

  /**
   * Creates a new DataMigrationRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DataMigrationRequestAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder newBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder();
    } else {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DataMigrationRequestAvroModel RecordBuilder by copying an existing DataMigrationRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DataMigrationRequestAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder newBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel other) {
    if (other == null) {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder();
    } else {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DataMigrationRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataMigrationRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<DataMigrationRequestAvroModel> {

    private java.lang.String sagaId;
    private long dataMigrationId;
    private java.lang.String transferId;
    private com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel SourceContentData;
    private com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder SourceContentDataBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[0].schema(), other.sagaId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.dataMigrationId)) {
        this.dataMigrationId = data().deepCopy(fields()[1].schema(), other.dataMigrationId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.transferId)) {
        this.transferId = data().deepCopy(fields()[2].schema(), other.transferId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.SourceContentData)) {
        this.SourceContentData = data().deepCopy(fields()[3].schema(), other.SourceContentData);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasSourceContentDataBuilder()) {
        this.SourceContentDataBuilder = com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.newBuilder(other.getSourceContentDataBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing DataMigrationRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[0].schema(), other.sagaId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dataMigrationId)) {
        this.dataMigrationId = data().deepCopy(fields()[1].schema(), other.dataMigrationId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.transferId)) {
        this.transferId = data().deepCopy(fields()[2].schema(), other.transferId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.SourceContentData)) {
        this.SourceContentData = data().deepCopy(fields()[3].schema(), other.SourceContentData);
        fieldSetFlags()[3] = true;
      }
      this.SourceContentDataBuilder = null;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[0], value);
      this.sagaId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dataMigrationId' field.
      * @return The value.
      */
    public long getDataMigrationId() {
      return dataMigrationId;
    }


    /**
      * Sets the value of the 'dataMigrationId' field.
      * @param value The value of 'dataMigrationId'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder setDataMigrationId(long value) {
      validate(fields()[1], value);
      this.dataMigrationId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'dataMigrationId' field has been set.
      * @return True if the 'dataMigrationId' field has been set, false otherwise.
      */
    public boolean hasDataMigrationId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dataMigrationId' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder clearDataMigrationId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'transferId' field.
      * @return The value.
      */
    public java.lang.String getTransferId() {
      return transferId;
    }


    /**
      * Sets the value of the 'transferId' field.
      * @param value The value of 'transferId'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder setTransferId(java.lang.String value) {
      validate(fields()[2], value);
      this.transferId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'transferId' field has been set.
      * @return True if the 'transferId' field has been set, false otherwise.
      */
    public boolean hasTransferId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'transferId' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder clearTransferId() {
      transferId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'SourceContentData' field.
      * @return The value.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel getSourceContentData() {
      return SourceContentData;
    }


    /**
      * Sets the value of the 'SourceContentData' field.
      * @param value The value of 'SourceContentData'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder setSourceContentData(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel value) {
      validate(fields()[3], value);
      this.SourceContentDataBuilder = null;
      this.SourceContentData = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'SourceContentData' field has been set.
      * @return True if the 'SourceContentData' field has been set, false otherwise.
      */
    public boolean hasSourceContentData() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'SourceContentData' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder getSourceContentDataBuilder() {
      if (SourceContentDataBuilder == null) {
        if (hasSourceContentData()) {
          setSourceContentDataBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.newBuilder(SourceContentData));
        } else {
          setSourceContentDataBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.newBuilder());
        }
      }
      return SourceContentDataBuilder;
    }

    /**
     * Sets the Builder instance for the 'SourceContentData' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder setSourceContentDataBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder value) {
      clearSourceContentData();
      SourceContentDataBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'SourceContentData' field has an active Builder instance
     * @return True if the 'SourceContentData' field has an active Builder instance
     */
    public boolean hasSourceContentDataBuilder() {
      return SourceContentDataBuilder != null;
    }

    /**
      * Clears the value of the 'SourceContentData' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.DataMigrationRequestAvroModel.Builder clearSourceContentData() {
      SourceContentData = null;
      SourceContentDataBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DataMigrationRequestAvroModel build() {
      try {
        DataMigrationRequestAvroModel record = new DataMigrationRequestAvroModel();
        record.sagaId = fieldSetFlags()[0] ? this.sagaId : (java.lang.String) defaultValue(fields()[0]);
        record.dataMigrationId = fieldSetFlags()[1] ? this.dataMigrationId : (java.lang.Long) defaultValue(fields()[1]);
        record.transferId = fieldSetFlags()[2] ? this.transferId : (java.lang.String) defaultValue(fields()[2]);
        if (SourceContentDataBuilder != null) {
          try {
            record.SourceContentData = this.SourceContentDataBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("SourceContentData"));
            throw e;
          }
        } else {
          record.SourceContentData = fieldSetFlags()[3] ? this.SourceContentData : (com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel) defaultValue(fields()[3]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DataMigrationRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DataMigrationRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DataMigrationRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DataMigrationRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










