/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.brunosong.transfer.system.kafka.transfer.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SourceContentDataAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5857021901785051953L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SourceContentDataAvroModel\",\"namespace\":\"com.brunosong.transfer.system.kafka.transfer.avro.model\",\"fields\":[{\"name\":\"sourceId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"jsonData\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SourceContentDataAvroModel> ENCODER =
      new BinaryMessageEncoder<SourceContentDataAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SourceContentDataAvroModel> DECODER =
      new BinaryMessageDecoder<SourceContentDataAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SourceContentDataAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SourceContentDataAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SourceContentDataAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SourceContentDataAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SourceContentDataAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SourceContentDataAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SourceContentDataAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SourceContentDataAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String sourceId;
  private java.nio.ByteBuffer jsonData;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SourceContentDataAvroModel() {}

  /**
   * All-args constructor.
   * @param sourceId The new value for sourceId
   * @param jsonData The new value for jsonData
   */
  public SourceContentDataAvroModel(java.lang.String sourceId, java.nio.ByteBuffer jsonData) {
    this.sourceId = sourceId;
    this.jsonData = jsonData;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sourceId;
    case 1: return jsonData;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sourceId = value$ != null ? value$.toString() : null; break;
    case 1: jsonData = (java.nio.ByteBuffer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sourceId' field.
   * @return The value of the 'sourceId' field.
   */
  public java.lang.String getSourceId() {
    return sourceId;
  }


  /**
   * Sets the value of the 'sourceId' field.
   * @param value the value to set.
   */
  public void setSourceId(java.lang.String value) {
    this.sourceId = value;
  }

  /**
   * Gets the value of the 'jsonData' field.
   * @return The value of the 'jsonData' field.
   */
  public java.nio.ByteBuffer getJsonData() {
    return jsonData;
  }


  /**
   * Sets the value of the 'jsonData' field.
   * @param value the value to set.
   */
  public void setJsonData(java.nio.ByteBuffer value) {
    this.jsonData = value;
  }

  /**
   * Creates a new SourceContentDataAvroModel RecordBuilder.
   * @return A new SourceContentDataAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder newBuilder() {
    return new com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder();
  }

  /**
   * Creates a new SourceContentDataAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SourceContentDataAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder newBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder other) {
    if (other == null) {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder();
    } else {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new SourceContentDataAvroModel RecordBuilder by copying an existing SourceContentDataAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new SourceContentDataAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder newBuilder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel other) {
    if (other == null) {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder();
    } else {
      return new com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for SourceContentDataAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SourceContentDataAvroModel>
    implements org.apache.avro.data.RecordBuilder<SourceContentDataAvroModel> {

    private java.lang.String sourceId;
    private java.nio.ByteBuffer jsonData;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sourceId)) {
        this.sourceId = data().deepCopy(fields()[0].schema(), other.sourceId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.jsonData)) {
        this.jsonData = data().deepCopy(fields()[1].schema(), other.jsonData);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing SourceContentDataAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sourceId)) {
        this.sourceId = data().deepCopy(fields()[0].schema(), other.sourceId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.jsonData)) {
        this.jsonData = data().deepCopy(fields()[1].schema(), other.jsonData);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'sourceId' field.
      * @return The value.
      */
    public java.lang.String getSourceId() {
      return sourceId;
    }


    /**
      * Sets the value of the 'sourceId' field.
      * @param value The value of 'sourceId'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder setSourceId(java.lang.String value) {
      validate(fields()[0], value);
      this.sourceId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sourceId' field has been set.
      * @return True if the 'sourceId' field has been set, false otherwise.
      */
    public boolean hasSourceId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sourceId' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder clearSourceId() {
      sourceId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'jsonData' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getJsonData() {
      return jsonData;
    }


    /**
      * Sets the value of the 'jsonData' field.
      * @param value The value of 'jsonData'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder setJsonData(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.jsonData = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'jsonData' field has been set.
      * @return True if the 'jsonData' field has been set, false otherwise.
      */
    public boolean hasJsonData() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'jsonData' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.transfer.avro.model.SourceContentDataAvroModel.Builder clearJsonData() {
      jsonData = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SourceContentDataAvroModel build() {
      try {
        SourceContentDataAvroModel record = new SourceContentDataAvroModel();
        record.sourceId = fieldSetFlags()[0] ? this.sourceId : (java.lang.String) defaultValue(fields()[0]);
        record.jsonData = fieldSetFlags()[1] ? this.jsonData : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SourceContentDataAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<SourceContentDataAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SourceContentDataAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<SourceContentDataAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sourceId);

    out.writeBytes(this.jsonData);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sourceId = in.readString();

      this.jsonData = in.readBytes(this.jsonData);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sourceId = in.readString();
          break;

        case 1:
          this.jsonData = in.readBytes(this.jsonData);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










