/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.brunosong.transfer.system.kafka.datamigration.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DataMigrationResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7302121125381044223L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataMigrationResponseAvroModel\",\"namespace\":\"com.brunosong.transfer.system.kafka.datamigration.avro.model\",\"fields\":[{\"name\":\"transferId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"transferStatus\",\"type\":{\"type\":\"enum\",\"name\":\"TransferStatus\",\"symbols\":[\"PENDING\",\"SENT\",\"PROCESSED\",\"SUCCESS\",\"FAILED\"]}},{\"name\":\"message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DataMigrationResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<DataMigrationResponseAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DataMigrationResponseAvroModel> DECODER =
      new BinaryMessageDecoder<DataMigrationResponseAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DataMigrationResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DataMigrationResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DataMigrationResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DataMigrationResponseAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DataMigrationResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DataMigrationResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DataMigrationResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DataMigrationResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String transferId;
  private com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus transferStatus;
  private java.lang.String message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DataMigrationResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param transferId The new value for transferId
   * @param transferStatus The new value for transferStatus
   * @param message The new value for message
   */
  public DataMigrationResponseAvroModel(java.lang.String transferId, com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus transferStatus, java.lang.String message) {
    this.transferId = transferId;
    this.transferStatus = transferStatus;
    this.message = message;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transferId;
    case 1: return transferStatus;
    case 2: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transferId = value$ != null ? value$.toString() : null; break;
    case 1: transferStatus = (com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus)value$; break;
    case 2: message = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transferId' field.
   * @return The value of the 'transferId' field.
   */
  public java.lang.String getTransferId() {
    return transferId;
  }


  /**
   * Sets the value of the 'transferId' field.
   * @param value the value to set.
   */
  public void setTransferId(java.lang.String value) {
    this.transferId = value;
  }

  /**
   * Gets the value of the 'transferStatus' field.
   * @return The value of the 'transferStatus' field.
   */
  public com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus getTransferStatus() {
    return transferStatus;
  }


  /**
   * Sets the value of the 'transferStatus' field.
   * @param value the value to set.
   */
  public void setTransferStatus(com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus value) {
    this.transferStatus = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.String getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.String value) {
    this.message = value;
  }

  /**
   * Creates a new DataMigrationResponseAvroModel RecordBuilder.
   * @return A new DataMigrationResponseAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder newBuilder() {
    return new com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder();
  }

  /**
   * Creates a new DataMigrationResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DataMigrationResponseAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder newBuilder(com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder other) {
    if (other == null) {
      return new com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder();
    } else {
      return new com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DataMigrationResponseAvroModel RecordBuilder by copying an existing DataMigrationResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DataMigrationResponseAvroModel RecordBuilder
   */
  public static com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder newBuilder(com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel other) {
    if (other == null) {
      return new com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder();
    } else {
      return new com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DataMigrationResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataMigrationResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<DataMigrationResponseAvroModel> {

    private java.lang.String transferId;
    private com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus transferStatus;
    private java.lang.String message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transferId)) {
        this.transferId = data().deepCopy(fields()[0].schema(), other.transferId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transferStatus)) {
        this.transferStatus = data().deepCopy(fields()[1].schema(), other.transferStatus);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DataMigrationResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transferId)) {
        this.transferId = data().deepCopy(fields()[0].schema(), other.transferId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transferStatus)) {
        this.transferStatus = data().deepCopy(fields()[1].schema(), other.transferStatus);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.message)) {
        this.message = data().deepCopy(fields()[2].schema(), other.message);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'transferId' field.
      * @return The value.
      */
    public java.lang.String getTransferId() {
      return transferId;
    }


    /**
      * Sets the value of the 'transferId' field.
      * @param value The value of 'transferId'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder setTransferId(java.lang.String value) {
      validate(fields()[0], value);
      this.transferId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transferId' field has been set.
      * @return True if the 'transferId' field has been set, false otherwise.
      */
    public boolean hasTransferId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transferId' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder clearTransferId() {
      transferId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transferStatus' field.
      * @return The value.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus getTransferStatus() {
      return transferStatus;
    }


    /**
      * Sets the value of the 'transferStatus' field.
      * @param value The value of 'transferStatus'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder setTransferStatus(com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus value) {
      validate(fields()[1], value);
      this.transferStatus = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transferStatus' field has been set.
      * @return True if the 'transferStatus' field has been set, false otherwise.
      */
    public boolean hasTransferStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transferStatus' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder clearTransferStatus() {
      transferStatus = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.String getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder setMessage(java.lang.String value) {
      validate(fields()[2], value);
      this.message = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.brunosong.transfer.system.kafka.datamigration.avro.model.DataMigrationResponseAvroModel.Builder clearMessage() {
      message = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DataMigrationResponseAvroModel build() {
      try {
        DataMigrationResponseAvroModel record = new DataMigrationResponseAvroModel();
        record.transferId = fieldSetFlags()[0] ? this.transferId : (java.lang.String) defaultValue(fields()[0]);
        record.transferStatus = fieldSetFlags()[1] ? this.transferStatus : (com.brunosong.transfer.system.kafka.datamigration.avro.model.TransferStatus) defaultValue(fields()[1]);
        record.message = fieldSetFlags()[2] ? this.message : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DataMigrationResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DataMigrationResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DataMigrationResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DataMigrationResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










