/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.brunosong.transfer.system.kafka.datamigration.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum TransferStatus implements org.apache.avro.generic.GenericEnumSymbol<TransferStatus> {
  PENDING, SENT, PROCESSED, SUCCESS, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransferStatus\",\"namespace\":\"com.brunosong.transfer.system.kafka.datamigration.avro.model\",\"symbols\":[\"PENDING\",\"SENT\",\"PROCESSED\",\"SUCCESS\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
