insert into main_chap ( chap_title, chap_type ) values ( 'ENGLISH 투케더 차시1' , 'ENG');
insert into main_chap ( chap_title, chap_type ) values ( 'ENGLISH 투케더 차시2' , 'ENG');
insert into main_chap ( chap_title, chap_type ) values ( 'ENGLISH 투케더 차시3' , 'ENG');
insert into main_chap ( chap_title, chap_type ) values ( 'ENGLISH 투케더 차시4' , 'ENG');
insert into main_chap ( chap_title, chap_type ) values ( '함께 한글 놀이해요 차시1' , 'KOR');
insert into main_chap ( chap_title, chap_type ) values ( '함께 한글 놀이해요 차시2' , 'KOR');
insert into main_chap ( chap_title, chap_type ) values ( '함께 한글 놀이해요 차시3' , 'KOR');
insert into main_chap ( chap_title, chap_type ) values ( '함께 한글 놀이해요 차시4' , 'KOR');
insert into main_chap ( chap_title, chap_type ) values ( '함께 한글 놀이해요 차시5' , 'KOR');
insert into main_chap ( chap_title, chap_type ) values ( '함께 한글 놀이해요 차시6' , 'KOR');
insert into main_chap ( chap_title, chap_type ) values ( '수학이 최고야 차시1' , 'MATH');
insert into main_chap ( chap_title, chap_type ) values ( '수학이 최고야 차시2' , 'MATH');
insert into main_chap ( chap_title, chap_type ) values ( '수학이 최고야 차시3' , 'MATH');
insert into main_chap ( chap_title, chap_type ) values ( '수학이 최고야 차시4' , 'MATH');
insert into main_chap ( chap_title, chap_type ) values ( '수학이 최고야 차시5' , 'MATH');
insert into main_chap ( chap_title, chap_type ) values ( '수학이 최고야 차시6' , 'MATH');