apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-dev-config
  namespace: transfer
data:
  my.cnf: |
    [mysqld]
    user=mysql
    bind-address=0.0.0.0
    default_authentication_plugin=mysql_native_password
    secure_file_priv=/var/lib/mysql
    max_connections=100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-dev-initdb
  namespace: transfer
data:
  init.sql: |
    GRANT ALL PRIVILEGES ON *.* TO 'brunosong'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
    CREATE DATABASE IF NOT EXISTS onlinecampus;
    CREATE DATABASE IF NOT EXISTS bootcamp;