server:
  port: 8888  # 기본 포트는 8888

spring:
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
      id: ${spring.application.name}:${spring.profiles.active:dev}:${random.uuid}
    compatibility-verifier:
      enabled: false
    config:
      server:
        git:
          uri: https://bitbucket.org/songbrunosong/brunosong-config/src/main/
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}


management:
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh

encrypt:
  key: ${SECRET_KEY}

logging:
  level:
    root: info